<?php

/**
* @file installation file of module erpal_projects_helper
*/

/**
* Add some base configuration for freelinking module integration
*/
function erpal_projects_helper_update_7001(&$sandbox) {
  variable_set('freelinking_default', 'nodetitle');
  variable_set('freelinking_match_syntax', 'double_bracket');
}

/**
* enable erpal_project_book feature to integrate books and projects
*/
function erpal_projects_helper_update_7002(&$sandbox) {
  module_enable(array('erpal_project_book'));
}